name: Python CI

on:
  push:
    branches: [ main, developer, master ]
  pull_request:
    branches: [ main, developer, master ]

jobs:
  build:
    env: 
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        cd AI_ChatBot
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock

    - name: Run tests
      run: |
        cd AI_ChatBot
        pytest test-chatbot.py -v
